<a href="https://colab.research.google.com/github/NeetuTiwari22/Advanced-python/blob/main/Advanced_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy ----> Numpy is an open-source library that is used for scintific calculations.

#Why Numpy is better than List ?
(1).Numpy homogeneous data type and List Hetrogeneous data type.

(2).Numpy take less memory while List take more memory.

(3).Numpy take Less Execution time while list take more time.

(4).Numpy has more functionality as compare to List.



In [ ]:
# !pip install numpy
import numpy as np

In [ ]:
a = [1,45,78,90]
type(a)

list

In [ ]:
b = np.array(a)
b

array([ 1, 45, 78, 90])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# **How can we check shape,size,dimension of an array**

In [ ]:
print("Total Rows and columns:",b.shape) ##shape = number(rows), number(columns)
print("total Elements:",b.size) # size = number(rows)*number(columns)
print("Dimension:",b.ndim) #ndim stands for n-dimensional
print("Data Type:",b.dtype)

Total Rows and columns: (3, 3)
total Elements: 9
Dimension: 2
Data Type: int64


# How can we create a usre-defined Array?

In [ ]:
a = []
size = int(input("Enter size of array:"))
for i in range(size):
    val = int(input("Enter number:"))
    a.append(val)
print("list:",a)
b = np.array(a)
b

Enter size of array:3
Enter number:12
Enter number:56
Enter number:889
list: [12, 56, 889]


array([ 12,  56, 889])

In [ ]:
a = (1,2,3)
b = np.array(a)
b

array([1, 2, 3])

#**Function in Numpy**

In [ ]:
#(1). Zeros()---->it wll create an array in which all the values are 0 in either
# on dimensional or multi dimensional.

In [ ]:
a = np.zeros(4)
a

array([0., 0., 0., 0.])

In [ ]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#(2).onces()--> It will create an array in which all the value are 1 in either
#one dimensional or multi- dimensional


In [ ]:
a = np.ones(4)
a

array([1., 1., 1., 1.])

In [ ]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#(3). eye()---> it will create an array in which digonal positional element
# will be 1 and rest all are 0.
a = np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
#(4).diag()--->it will create an array in which we can customize
# our digonal positinal elements.


In [ ]:
a = np.array([1,34,78,90])
a

array([ 1, 34, 78, 90])

In [ ]:
b = np.diag(a)
b

array([[ 1,  0,  0,  0],
       [ 0, 34,  0,  0],
       [ 0,  0, 78,  0],
       [ 0,  0,  0, 90]])

In [ ]:
#(5). Random Module
#(a).Randint--> it will create random number in a given range.
# syntax: np.random.randint(min_val, max_val,total_numbers)

In [ ]:
a = np.random.randint(1,10,3)
a

array([4, 4, 6])

In [ ]:
#(b). Rand()-->it will create an array in which at the value will be
# from range 0 to 1.

In [ ]:
a = np.random.rand(4)
a

array([0.61537129, 0.0037844 , 0.48445466, 0.16637046])

In [ ]:
#(c). seed()-->it will fix our random generated data.

In [ ]:
np.random.seed(15)
a = np.random.randint(1,10,3)
a

array([9, 6, 6])

#View Vs Copy

In [ ]:
# View means modification in original data.
# copy means modification in duplicate data that will not reflect original data.

In [ ]:
a = np.array ([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
b = a[2:5]
b[:] = 0
b

array([0, 0, 0])

In [ ]:
a

array([1, 2, 0, 0, 0, 6, 7, 8])

In [ ]:
a = np.array ([1,2,3,4,5,6,7,8])
b = a[2:5].copy()
b[:] = 0
b

array([0, 0, 0])

In [ ]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

#Reshaping the Array

In [ ]:
# n(rows)*n(columns) = n(total_elements)

In [ ]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [ ]:
b = a>10
a[b]

array([11, 12, 13, 14, 15])

In [ ]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [ ]:
a**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225])

In [ ]:
a**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000, 1331,
       1728, 2197, 2744, 3375])

In [ ]:
# total_elements = 15
# 1*15,15*1
# 5*3,3*5

In [ ]:
a.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
a.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [ ]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [ ]:
a+b

array([[ 6,  8],
       [10, 12]])

In [ ]:
a-b

array([[-4, -4],
       [-4, -4]])

In [ ]:
a.dot(b)# for matrix multiplication

array([[19, 22],
       [43, 50]])

In [ ]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

#Unique Method

In [ ]:
#Unique()-->it will return 3 arrays.
# (a). arr-->unique element of array.
# (b). return_index=true--->Indexing of unique element
# (c). return_counts= True-->Occurance of Frequency of  unique element

In [ ]:
a = np.array([1,2,1,1,1,1,3,2,3,3,3,3,4])
np.unique(a, return_index=True , return_counts=True)

(array([1, 2, 3, 4]), array([ 0,  1,  6, 12]), array([5, 2, 5, 1]))

In [ ]:
# linspace()-->it will return an array in which gap of values will be equal
#syntax: np.linspace(min_number, max_number, total_number)

In [ ]:
a = np.linspace(1,10,3)
a

array([ 1. ,  5.5, 10. ])

In [ ]:
# Hstack() and vstack()--->
# Hstack-->it will combined horizontally all array.
# Vstack-->it will combined vertically all array.

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([9,10,11,12])

In [ ]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#pandas-->Pandas is an open-source library of python that is used for handle data maniuplations.

In [ ]:
#!pip install pandas
import pandas as pd

In [ ]:
# Data Structure of pandas
# (a).series-->it is one dimensional array and it shows only values.
# (b).DataFrame--->it is multi-dimensional array and it contains values with column name.

In [ ]:
a = pd.Series([1,45,78,90])
a

0     1
1    45
2    78
3    90
dtype: int64

In [ ]:
type(a)

pandas.core.series.Series

In [ ]:
# (b).Dataframe
a={
    "Emp_ID":[1,2,3,4,5],
    "Name":['Sam','Raj','Mohit','Aniket','Pallavi'],
    "Department":['HR','IT','HR','IT','HR'],
    "Salary":[20000,25000,30000,32000,27000]
}

In [ ]:
df = pd.DataFrame(a)
df

Emp_ID     Name Department  Salary
0       1      Sam         HR   20000
1       2      Raj         IT   25000
2       3    Mohit         HR   30000
3       4   Aniket         IT   32000
4       5  Pallavi         HR   27000

In [ ]:
df.to_csv("/content/Emp_data.csv")

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/covid_toy - covid_toy.csv")
df

age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [ ]:
# top 5 data
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
# bottom 5 data
df.tail()

age  gender  fever   cough       city has_covid
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

In [ ]:
#Random indexed data
df.sample(4)

age  gender  fever   cough    city has_covid
11   65  Female   98.0    Mild  Mumbai       Yes
25   23    Male    NaN    Mild  Mumbai        No
91   38    Male    NaN    Mild   Delhi       Yes
74   34  Female  104.0  Strong   Delhi        No

In [ ]:
df = pd.read_csv("/content/placement - placement.csv")
df

cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [ ]:
df.head(5)

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [ ]:
df.tail()

cgpa  resume_score  placed
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

In [ ]:
df.describe() # statically view of data

cgpa  resume_score      placed
count  100.0000    100.000000  100.000000
mean     6.9422      6.930500    0.500000
std      1.1192      0.979608    0.502519
min      5.2700      4.950000    0.000000
25%      5.9800      6.190000    0.000000
50%      6.6200      7.055000    0.500000
75%      8.0450      7.640000    1.000000
max      9.4000      9.060000    1.000000

In [ ]:
df.info() #Data type information(all over information)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   cgpa          100 non-null    float64
 1   resume_score  100 non-null    float64
 2   placed        100 non-null    int64  
dtypes: float64(2), int64(1)
memory usage: 2.5 KB


In [ ]:
top_left_corner = df.iloc[:4,:3]#iloc[row_range ,column_range]
top_left_corner

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1

In [ ]:
df.loc[1:3, ['cgpa' ,'placed']]#loc[row_range, column_names]

cgpa  placed
1  6.17       0
2  8.27       1
3  6.88       1

In [ ]:
p = df.dtypes #columns type
p

cgpa            float64
resume_score    float64
placed            int64
dtype: object

In [ ]:
b = df.empty# it return true if there any missing data in dataframe otherwise return false.
b

False

In [ ]:
df.isnull().sum()##for check missing value.


cgpa            0
resume_score    0
placed          0
dtype: int64

In [ ]:
df=df.dropna()##for remove missing values.


In [ ]:
i = df.ndim## number of axes (is is 2)
i

2

In [ ]:
t = df.shape #shape = number(rows) , number(colums)
t

(100, 3)

In [ ]:
d = df.size   #row count * column count
d

300

In [ ]:
a = df.values  #get a numpy array for df
a

array([[8.14, 6.52, 1.  ],
       [6.17, 5.17, 0.  ],
       [8.27, 8.86, 1.  ],
       [6.88, 7.27, 1.  ],
       [7.52, 7.3 , 1.  ],
       [8.77, 6.19, 1.  ],
       [5.34, 7.09, 0.  ],
       [6.56, 6.29, 0.  ],
       [6.32, 6.71, 0.  ],
       [7.69, 7.12, 1.  ],
       [6.18, 6.35, 0.  ],
       [5.44, 6.54, 0.  ],
       [6.09, 7.01, 0.  ],
       [8.5 , 5.09, 1.  ],
       [7.51, 6.25, 1.  ],
       [8.88, 5.93, 1.  ],
       [8.04, 7.64, 1.  ],
       [7.81, 8.71, 1.  ],
       [5.94, 5.88, 0.  ],
       [6.75, 8.11, 1.  ],
       [5.8 , 8.06, 0.  ],
       [6.53, 7.64, 0.  ],
       [6.16, 5.77, 0.  ],
       [6.05, 7.13, 0.  ],
       [8.22, 6.18, 1.  ],
       [7.76, 5.68, 1.  ],
       [6.27, 6.47, 0.  ],
       [5.51, 6.15, 0.  ],
       [7.46, 7.67, 1.  ],
       [6.19, 7.3 , 0.  ],
       [7.36, 7.15, 1.  ],
       [5.92, 7.02, 0.  ],
       [5.87, 7.96, 0.  ],
       [8.43, 7.73, 1.  ],
       [8.87, 7.19, 1.  ],
       [8.07, 7.48, 1.  ],
       [8.16, 7.56, 1.  ],
 

In [ ]:
df = df.copy()

In [ ]:
p = df.sort_values(by = 'resume_score')
p

cgpa  resume_score  placed
94  8.01          4.95       1
87  5.62          5.05       0
13  8.50          5.09       1
41  8.68          5.15       1
1   6.17          5.17       0
..   ...           ...     ...
17  7.81          8.71       1
38  6.00          8.72       0
65  6.04          8.75       0
2   8.27          8.86       1
69  8.06          9.06       1

[100 rows x 3 columns]

In [ ]:
r = df.sort_index()
r

cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [ ]:
x = df.astype(int) #type conversion
df['cgpa'] = df['cgpa'].astype(int)
df

cgpa  resume_score  placed
0      8          6.52       1
1      6          5.17       0
2      8          8.86       1
3      6          7.27       1
4      7          7.30       1
..   ...           ...     ...
95     6          6.38       0
96     8          7.76       1
97     6          7.78       0
98     8          5.63       1
99     6          6.61       0

[100 rows x 3 columns]

In [ ]:
x = df.astype(int) #type conversion
df['resume_score'] = df['resume_score'].astype(int)
df

cgpa  resume_score  placed
0      8             6       1
1      6             5       0
2      8             8       1
3      6             7       1
4      7             7       1
..   ...           ...     ...
95     6             6       0
96     8             7       1
97     6             7       0
98     8             5       1
99     6             6       0

[100 rows x 3 columns]

In [ ]:
t = df.add(4)
df['cgpa']= df['cgpa'].add(4)
t

cgpa  resume_score  placed
0     24            10       5
1     22             9       4
2     24            12       5
3     22            11       5
4     23            11       5
..   ...           ...     ...
95    22            10       4
96    24            11       5
97    22            11       4
98    24             9       5
99    22            10       4

[100 rows x 3 columns]

In [ ]:
s = df.count()
s

cgpa            100
resume_score    100
placed          100
dtype: int64

In [ ]:
s = df.max()
s

cgpa            25
resume_score     9
placed           1
dtype: int64

In [ ]:
p = df.min()
p

cgpa            21
resume_score     4
placed           0
dtype: int64

In [ ]:
r = df['cgpa'].mean() #
r

np.float64(22.47)

In [ ]:
s = df.median()
s

cgpa            22.0
resume_score     7.0
placed           0.5
dtype: float64

In [ ]:
s = df.filter(items = ['cgpa' , 'placed'])
s
df[['cgpa' , 'placed']] ##second option of filtering


cgpa  placed
0     24       1
1     22       0
2     24       1
3     22       1
4     23       1
..   ...     ...
95    22       0
96    24       1
97    22       0
98    24       1
99    22       0

[100 rows x 2 columns]

In [ ]:
s = df.filter(items = [5,6] , axis = 0) ##axis = 0 means row wise operation
s

cgpa  resume_score  placed
5    24             6       1
6    21             7       0

In [ ]:
s = df.to_dict() #save in dictionary
s

{'cgpa': {0: 24,
  1: 22,
  2: 24,
  3: 22,
  4: 23,
  5: 24,
  6: 21,
  7: 22,
  8: 22,
  9: 23,
  10: 22,
  11: 21,
  12: 22,
  13: 24,
  14: 23,
  15: 24,
  16: 24,
  17: 23,
  18: 21,
  19: 22,
  20: 21,
  21: 22,
  22: 22,
  23: 22,
  24: 24,
  25: 23,
  26: 22,
  27: 21,
  28: 23,
  29: 22,
  30: 23,
  31: 21,
  32: 21,
  33: 24,
  34: 24,
  35: 24,
  36: 24,
  37: 25,
  38: 22,
  39: 23,
  40: 24,
  41: 24,
  42: 22,
  43: 24,
  44: 21,
  45: 24,
  46: 21,
  47: 23,
  48: 21,
  49: 21,
  50: 24,
  51: 22,
  52: 21,
  53: 22,
  54: 21,
  55: 22,
  56: 22,
  57: 22,
  58: 22,
  59: 21,
  60: 21,
  61: 22,
  62: 21,
  63: 24,
  64: 23,
  65: 22,
  66: 24,
  67: 22,
  68: 22,
  69: 24,
  70: 23,
  71: 23,
  72: 23,
  73: 21,
  74: 21,
  75: 22,
  76: 25,
  77: 21,
  78: 21,
  79: 21,
  80: 23,
  81: 22,
  82: 23,
  83: 23,
  84: 21,
  85: 22,
  86: 22,
  87: 21,
  88: 24,
  89: 21,
  90: 21,
  91: 24,
  92: 21,
  93: 25,
  94: 24,
  95: 22,
  96: 24,
  97: 22,
  98: 24,
  99: 22},
 

In [ ]:
q = df.to_string()  #save in string
q


'    cgpa  resume_score  placed\n0     24             6       1\n1     22             5       0\n2     24             8       1\n3     22             7       1\n4     23             7       1\n5     24             6       1\n6     21             7       0\n7     22             6       0\n8     22             6       0\n9     23             7       1\n10    22             6       0\n11    21             6       0\n12    22             7       0\n13    24             5       1\n14    23             6       1\n15    24             5       1\n16    24             7       1\n17    23             8       1\n18    21             5       0\n19    22             8       1\n20    21             8       0\n21    22             7       0\n22    22             5       0\n23    22             7       0\n24    24             6       1\n25    23             5       1\n26    22             6       0\n27    21             6       0\n28    23             7       1\n29    22             7       0\n30    2

In [ ]:
e = df.to_csv("/content/placement - placement.csv")

In [ ]:
idx = df.columns
idx

Index(['cgpa', 'resume_score', 'placed'], dtype='object')

In [ ]:
label = df.columns[0]# first column label
label

'cgpa'

In [ ]:
p = df.columns.tolist() #list of columns labels
p

['cgpa', 'resume_score', 'placed']

In [ ]:
q = df.columns.values  ## array of columns labels
q

array(['cgpa', 'resume_score', 'placed'], dtype=object)

In [ ]:
p = df.rename(columns = {'cgpa':'updated_cgpa',
                       'resume_score':'semester_marks'}) #how to rename columns
p


updated_cgpa  semester_marks  placed
0             24               6       1
1             22               5       0
2             24               8       1
3             22               7       1
4             23               7       1
..           ...             ...     ...
95            22               6       0
96            24               7       1
97            22               7       0
98            24               5       1
99            22               6       0

[100 rows x 3 columns]

In [ ]:
df['Cgpan'] = df ['cgpa'].astype(int)
df

cgpa  resume_score  placed  Cgpan
0     24             6       1     24
1     22             5       0     22
2     24             8       1     24
3     22             7       1     22
4     23             7       1     23
..   ...           ...     ...    ...
95    22             6       0     22
96    24             7       1     24
97    22             7       0     22
98    24             5       1     24
99    22             6       0     22

[100 rows x 4 columns]

In [ ]:
a = df.drop(columns = ['Cgpan','placed'])
a

cgpa  resume_score
0     24             6
1     22             5
2     24             8
3     22             7
4     23             7
..   ...           ...
95    22             6
96    24             7
97    22             7
98    24             5
99    22             6

[100 rows x 2 columns]

In [ ]:
df['New'] = df['cgpa'].where(df['cgpa']>6 , other=0)
df.sample(11)

cgpa  resume_score  placed  Cgpan  New
21    22             7       0     22   22
9     23             7       1     23   23
30    23             7       1     23   23
95    22             6       0     22   22
39    23             6       1     23   23
7     22             6       0     22   22
41    24             5       1     24   24
50    24             6       1     24   24
68    22             7       0     22   22
47    23             8       1     23   23
65    22             8       0     22   22

In [ ]:
#df merging , containing
data1 = {
    "name" : ["Sally", "Marry", "John"],
    "age" :  [50,40,30]
}
data2 = {
    "name" : ["Sally", "Peter", "Micky"],
    "age" :  [77,44,22]
}
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

newdf = df1.merge(df2, how='right')
newdf

name  age
0  Sally   77
1  Peter   44
2  Micky   22

In [ ]:
newdf = df1.merge(df2, how='left')
newdf

name  age
0  Sally   50
1  Marry   40
2   John   30

In [ ]:
# containing
data1 = {'Name':['Jai','Princi','Gaurav','Anuj'],
          'age' : [17,14,12,52],
          'Address' : ['Nagpur','Kanpur','Allahabad','Kannauj'],
          'Qualification' : ['Msc','MA','MCA','Phd']}

data2 = {
          'Name':['Abhi','Ayushi','Dhiraj','Hitesh'],
          'age' : [17,14,12,52],
          'Address' : ['Nagpur','Kanpur','Allahabad','Kannauj'],
          'Qualification' : ['Btech','B.A','Bcom','B.hons']}


In [ ]:
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
df1

Name  age    Address Qualification
0     Jai   17     Nagpur           Msc
1  Princi   14     Kanpur            MA
2  Gaurav   12  Allahabad           MCA
3    Anuj   52    Kannauj           Phd

In [ ]:
df2

Name  age    Address Qualification
0    Abhi   17     Nagpur         Btech
1  Ayushi   14     Kanpur           B.A
2  Dhiraj   12  Allahabad          Bcom
3  Hitesh   52    Kannauj        B.hons

In [ ]:
new_df = pd.concat([df1,df2])
new_df

Name  age    Address Qualification
0     Jai   17     Nagpur           Msc
1  Princi   14     Kanpur            MA
2  Gaurav   12  Allahabad           MCA
3    Anuj   52    Kannauj           Phd
0    Abhi   17     Nagpur         Btech
1  Ayushi   14     Kanpur           B.A
2  Dhiraj   12  Allahabad          Bcom
3  Hitesh   52    Kannauj        B.hons

In [ ]:
df = pd.merge(df1,df2, on='Address',how = 'inner')
df

Name_x  age_x    Address Qualification_x  Name_y  age_y Qualification_y
0     Jai     17     Nagpur             Msc    Abhi     17           Btech
1  Princi     14     Kanpur              MA  Ayushi     14             B.A
2  Gaurav     12  Allahabad             MCA  Dhiraj     12            Bcom
3    Anuj     52    Kannauj             Phd  Hitesh     52          B.hons