<a href="https://colab.research.google.com/github/NeetuTiwari22/Advanced-python/blob/main/Numpy_Questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
# 1
arr1 = np.arange(5, 51, 5)
print(arr1)

[ 5 10 15 20 25 30 35 40 45 50]


In [4]:
# 2
arr2 = np.ones((4, 3))
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
# 3. 6 equally spaced values between 0 and 1.
arr3 = np.linspace(0, 1, 6)
print(arr3)

[0.  0.2 0.4 0.6 0.8 1. ]


In [6]:
# 4. Create a 3×3 identity matrix.
arr4 = np.eye(3)
print(arr4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
# 5. shape, size, number of dimensions, and data type of a given array.
print(arr1.shape)
print(arr1.size)
print(arr1.ndim)
print(arr1.dtype)

(10,)
10
1
int64


In [8]:
# 6. the Python list [10, 20, 30, 40, 50] into a NumPy array.
lst = [10, 20, 30, 40, 50]
arr5 = np.array(lst)
print(arr5)


[10 20 30 40 50]


In [9]:
# 7. 1D array of 16 elements into a 4×4 matrix.
arr6 = np.arange(1, 17)
matrix = arr6.reshape(4, 4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [10]:
# 8. 2D array into 1D using both flatten() and ravel().
flat1 = matrix.flatten()
flat2 = matrix.ravel()

print(flat1)
print(flat2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [11]:
# 9. Access the middle element of a 1D array.
arr7 = np.array([10, 20, 30, 40, 50])
middle = arr7[len(arr7)//2]
print(middle)

30


In [12]:
# 10. a NumPy array without using loops.
rev = arr7[::-1]
print(rev)

[50 40 30 20 10]


In [13]:
# 11.all even-indexed elements
print(arr7[::2])

[10 30 50]


In [15]:
# 12. the last column from a 2D array.
print(matrix[:, -1])

[ 4  8 12 16]


In [16]:
# 13. 1D array to get alternate elements starting from index 1.
print(arr7[1::2])

[20 40]


In [17]:
# 14. Extract a 2×2 sub-matrix from a 3×3 matrix.
mat3 = np.arange(1, 10).reshape(3, 3)
sub = mat3[:2, :2]
print(sub)

[[1 2]
 [4 5]]


In [18]:
# 15. Print all elements except the first and last element of an array.
print(arr7[1:-1])


[20 30 40]


In [19]:
# 16. greater than 25 from a NumPy array.
print(arr1[arr1 > 25])

[30 35 40 45 50]


In [20]:
# 17.negative values in an array with 0.
arr8 = np.array([10, -5, 20, -2, 30])
arr8[arr8 < 0] = 0
print(arr8)

[10  0 20  0 30]


In [21]:
# 18.Extract only the elements divisible by 3.
print(arr1[arr1 % 3 == 0])

[15 30 45]


In [22]:
# 19.Count how many elements are greater than the mean of the array.
mean_val = arr1.mean()
count = np.sum(arr1 > mean_val)
print(count)

5


In [23]:
# 20.Find the indices of elements where the value is equal to 50.
indices = np.where(arr1 == 50)
print(indices)

(array([9]),)


In [24]:
# 21.Add two NumPy arrays element-wise.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)

[5 7 9]


In [25]:
# 22. Perform matrix multiplication of two compatible matrices.
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
result = np.dot(m1, m2)
print(result)

[[19 22]
 [43 50]]


In [26]:
# 23.Add a scalar value 10 to every element of a NumPy array.
print(arr7 + 10)

[20 30 40 50 60]


In [27]:
# 24.Add a 1D array of shape (3,) to a 2D array of shape (2, 3) using broadcasting.
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])

arr1d = np.array([10, 20, 30])

print(arr2d + arr1d)

[[11 22 33]
 [14 25 36]]
